.TH yearcal 1
.SH NAME
yearcal \- print a calendar for one or more years
.SH SYNOPSIS
.B yearcal
.I year(s)...
.SH DESCRIPTION
.B yearcal
prints the calendar for
.IR year .
.I year
can be negative or positive, and is a Proleptic Gregorian year number.

The output of
.B yearcal
contains overstriking for boldface and underline and is suitable for running through
.B ul .
The first column is Sunday, and months are printed on the right-hand side.

.SH "SEE ALSO"
easter(1)
