#!/bin/sh -e
# (c) Copyright 2003,2019 Jonathan de Boyne Pollard. "Moral" rights asserted.
# For the copyright licence, see COPYING.
# This script requires the patch that changes the ${DNSCACHEIP} separator, which is incorporated into djbwares, and can also be found at <URL:http://jdebp.uk./Softwares/djbdns.html>.
t=${1?Missing type}
n=${2?Missing name}
s=${3?Missing server}
i=`dnsip $s`
DNSCACHEIP=${i:?Bad server name} exec dnsqr $t $n
