#!/bin/sh -e
# See http://jdebp.uk./FGA/slashpackage.html
if [ \! -d package ] || [ \! -d source ]
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi
./package/compile
exec ./package/upgrade
