#!/bin/sh -e
# See http://jdebp.eu./FGA/slashpackage.html
if [ \! -d package -o \! -d source ]
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi

# Atomically update the release directories ./command, ./library, ./include, and so forth.
# The build and release directories need not be on the same disc volume.
# And the files released must not be potentially overwritable and truncatable by the compiler/linker during subsequent builds.
install -d -- command manual config doc header library doc/commands

# ##############################################################################
# Build all of the ...{new} files in ./command, ./config, and ./manual.
cat package/commands1 package/commands8 | while read i
do
	rm -f -- command/"$i"{new}
	install -p -m 0755 -- build/"$i" command/"$i"{new}
	if objdump -a command/"$i"{new} >/dev/null 2>&1
	then
		 strip command/"$i"{new}
	fi
done
# All of the commands that have their own manual and guide pages
for section in 1 3 5 8
do
	cat package/commands${section} package/extra-manpages${section} | 
	while read i
	do
		rm -f -- manual/"$i".${section}{new}
		install -p -m 0644 -- build/"$i".${section} manual/"$i".${section}{new}
		rm -f -- doc/"$i".html{new}
		install -p -m 0644 -- build/"$i".html doc/"$i".html{new}
		rm -f -- doc/"$i".xml{new}
		install -p -m 0644 -- build/"$i".xml doc/commands/"$i".xml{new}
	done
done
# Aliased manual and guide pages
for section in 3
do
	cat package/aliases${section} | 
	while read c a
	do
		ln -f -- manual/"$c".${section}{new} manual/"$a".${section}{new}
		ln -f -- doc/"$c".html{new} doc/"$a".html{new}
		ln -f -- doc/commands/"$c".xml{new} doc/commands/"$a".xml{new}
	done
done
# Headers and libraries
cat package/headers | 
while read i
do
	rm -f -- header/"$i".h{new}
	install -p -m 0644 -- build/"$i".h header/"$i".h{new}
done
cat package/libraries | 
while read i
do
	rm -f -- library/"$i".h{new}
	install -p -m 0644 -- build/"$i".a library/"$i".a{new}
done
# Other guide pages
for i in COPYING
do
	rm -f -- doc/"$i"{new}
	install -p -m 0644 -- build/"$i" doc/"$i"{new}
done
for i in docbook-xml.css
do
	rm -f -- doc/commands/"$i"{new}
	install -p -m 0644 -- build/"$i" doc/commands/"$i"{new}
done
for i in dnsroots.global leapsecs.dat
do
	install -p -m 0644 -- build/"$i" config/"$i"{new}
done

# ##############################################################################
# Rename the ...{new} files in ./command, ./config, and ./manual.
cat package/commands1 package/commands8 | while read i
do
	mv -f -- command/"$i"{new} command/"$i"
done
# All of the commands that have their own manual and guide pages
for section in 1 3 5 8
do
	cat package/commands${section} package/extra-manpages${section} | 
	while read i
	do
		mv -f -- manual/"$i".${section}{new} manual/"$i".${section}
		mv -f -- doc/"$i".html{new} doc/"$i".html
		mv -f -- doc/commands/"$i".xml{new} doc/commands/"$i".xml
	done
done
# Aliased manual and guide pages
for section in 3
do
	cat package/aliases${section} | 
	while read c a
	do
		mv -f -- manual/"$a".${section}{new} manual/"$a".${section}
		mv -f -- doc/"$a".html{new} doc/"$a".html
		mv -f -- doc/commands/"$a".xml{new} doc/commands/"$a".xml
	done
done
# Headers and libraries
cat package/headers | 
while read i
do
	mv -f -- header/"$i".h{new} header/"$i".h
done
cat package/libraries | 
while read i
do
	mv -f -- library/"$i".a{new} library/"$i".a
done
# Other doco
for i in COPYING
do
	mv -f -- doc/"$i"{new} doc/"$i"
done
for i in docbook-xml.css
do
	mv -f -- doc/commands/"$i"{new} doc/commands/"$i"
done
for i in dnsroots.global leapsecs.dat
do
	mv -f -- config/"$i"{new} config/"$i"
done
