#!/bin/sh -e
# See http://jdebp.eu./FGA/slashpackage.html
if [ \! -d package ] || [ \! -d source ] 
then
	echo "You are not in the right directory." 1>&2 
	exit 100
fi
if ! test $# -ge 2
then
	echo "Two arguments are required." 1>&2 
	exit 100
fi

src="${1}"
dest="${2}"
absdest="`readlink -f "${dest}"`/"

# binaries and doco
for i in publicfile djbdns clockspeed ptyget ucspi-tcp daemontools multilog taiclockd libtai leapsecs djbdns-host
do
	install -d -m 0755 "${dest}"/"$i"/

	if test -s package/"$i".extra-manpages5
	then
		install -d -m 0755 "${dest}"/"$i"/usr/local/man/man5 
		while read j ;
		do
			ln -f -- "${src}"/man/man5/"$j".5 "${dest}"/"$i"/usr/local/man/man5/ 
		done < package/"$i".extra-manpages5 ;
	fi

	if test -s package/"$i".commands1 || test -s package/"$i".aliases1
	then
		install -d -m 0755 "${dest}"/"$i"/usr/local/bin 
	fi
	if test -s package/"$i".commands1
	then
		while read j ;
		do
			ln -f -- "${src}"/bin/"$j" "${dest}"/"$i"/usr/local/bin/ 
		done < package/"$i".commands1 ;
	fi
	if test -s package/"$i".aliases1
	then
		while read c a ;
		do
			ln -f -s "$c" "${dest}"/"$i"/usr/local/bin/"$a" 
		done < package/"$i".aliases1 ;
	fi

	if test -s package/"$i".commands8 || test -s package/"$i".aliases8
	then
		install -d -m 0755 "${dest}"/"$i"/usr/local/sbin 
	fi
	if test -s package/"$i".commands8
	then
		while read j ;
		do
			ln -f -- "${src}"/sbin/"$j" "${dest}"/"$i"/usr/local/sbin/ 
		done < package/"$i".commands8 ;
	fi
	if test -s package/"$i".aliases8
	then
		while read c a ;
		do
			ln -f -s "$c" "${dest}"/"$i"/usr/local/sbin/"$a" 
		done < package/"$i".aliases8 ;
	fi

	for section in 1 3 4 5 7 8
	do
		if test -s package/"$i".commands${section} || test -s package/"$i".aliases${section}
		then
			install -d -m 0755 "${dest}"/"$i"/usr/local/man/man${section} 
		fi
		if test -s package/"$i".commands${section}
		then
			while read j ;
			do
				ln -f -- "${src}"/man/man${section}/"$j".${section} "${dest}"/"$i"/usr/local/man/man${section}/ 
			done < package/"$i".commands${section} ;
		fi
		if test -s package/"$i".aliases${section}
		then
			while read c a ;
			do
				ln -f -s "$c".${section} "${dest}"/"$i"/usr/local/man/man${section}/"$a".${section} 
			done < package/"$i".aliases${section} ;
		fi
	done

	if test -s package/"$i".functions3 ;
	then
		install -d -m 0755 "${dest}"/"$i"/usr/local/man/man3 
		while read j ;
		do
			ln -f -- "${src}"/man/man3/"$j".3 "${dest}"/"$i"/usr/local/man/man3/ 
		done < package/"$i".functions3 ;
		while read c a ;
		do
			ln -f -- "${dest}"/"$i"/usr/local/man/man3/"$c".3 "${dest}"/"$i"/usr/local/man/man3/"$a".3 
		done < package/"$i".aliases3 ;
	fi

	if test -s package/"$i".headers ;
	then
		install -d -m 0755 "${dest}"/"$i"/usr/local/include
		while read j ;
		do
			ln -f -- "${src}"/include/"$j".h "${dest}"/"$i"/usr/local/include/ 
		done < package/"$i".headers ;
	fi

	if test -s package/"$i".libraries ;
	then
		install -d -m 0755 "${dest}"/"$i"/usr/local/lib
		while read j ;
		do
			ln -f -- "${src}"/lib/"$j".a "${dest}"/"$i"/usr/local/lib/ 
		done < package/"$i".libraries ;
	fi

done

case "`uname`" in
Linux)	prefix="usr" ;;
*BSD)	prefix="usr/local" ;;
esac
install -d -m 0755 "${dest}/leapsecs/${prefix}/share/libtai/" 
ln -f -- "${src}"/etc/leapsecs.dat "${dest}/leapsecs/${prefix}/share/libtai/"
